### ISSUE TITLE
Final Week Tasks

### ISSUE THREAD

**Issue by vikasTmz** [lagadic/visp_cao_editor#22]
### TODO:
- [x] Parse correctly generic CAO model (see here)
- [x] Save `Qt3DRender::QCamera` Settings into XML config file.
- [ ] Display face normals.
- [x] Choose the 3D points for the init config file.
- [ ] Switch model points when the displayed face normal is not correct.
- [ ] Fix bug: "run the application --> import CAO + save dialog make the application crash"
- [ ] Update README/Documentation for Qt-App.
- [ ] Remove unused icons.
- [ ] Help button.
- [ ] Get lod settings (length & area) using camera intrinsic & extrinsic properties & world coord.
